background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 7
    brightness = 0.5
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(88c0d0)
    inner_color = rgb(2e3440)
    font_color = rgb(d8dee9)
    placeholder_text = <i>Senha...</i>
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgb(d8dee9)
    font_size = 64
    font_family = JetBrains Mono
    position = 0, 100
    halign = center
    valign = center
}
